// <auto-generated />
using System;
using ChainflipInsights.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChainflipInsights.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20240429094126_AddSwapInfoTable")]
    partial class AddSwapInfoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ChainflipInsights.EntityFramework.BurnInfo", b =>
                {
                    b.Property<ulong>("BurnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("BurnId"));

                    b.Property<double>("BurnAmount")
                        .HasColumnType("double");

                    b.Property<ulong>("BurnBlock")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTimeOffset>("BurnDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BurnHash")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ExplorerUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BurnId");

                    b.HasIndex("BurnDate");

                    b.ToTable("burn_info", (string)null);
                });

            modelBuilder.Entity("ChainflipInsights.EntityFramework.EpochInfo", b =>
                {
                    b.Property<ulong>("EpochId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("EpochId"));

                    b.Property<DateTimeOffset>("EpochStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExplorerUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("MaxBid")
                        .HasColumnType("double");

                    b.Property<double>("MinimumBond")
                        .HasColumnType("double");

                    b.Property<double>("TotalBond")
                        .HasColumnType("double");

                    b.Property<double>("TotalRewards")
                        .HasColumnType("double");

                    b.HasKey("EpochId");

                    b.HasIndex("EpochStart");

                    b.ToTable("epoch_info", (string)null);
                });

            modelBuilder.Entity("ChainflipInsights.EntityFramework.FundingInfo", b =>
                {
                    b.Property<ulong>("FundingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("FundingId"));

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<ulong>("Epoch")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTimeOffset>("FundingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Validator")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.HasKey("FundingId");

                    b.HasIndex("FundingDate");

                    b.ToTable("funding_info", (string)null);
                });

            modelBuilder.Entity("ChainflipInsights.EntityFramework.LiquidityInfo", b =>
                {
                    b.Property<ulong>("LiquidityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("LiquidityId"));

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<double>("AmountUsd")
                        .HasColumnType("double");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ExplorerUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("LiquidityDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("LiquidityId");

                    b.HasIndex("Asset");

                    b.HasIndex("LiquidityDate");

                    b.ToTable("liquidity_info", (string)null);
                });

            modelBuilder.Entity("ChainflipInsights.EntityFramework.StakedInfo", b =>
                {
                    b.Property<ulong>("StakedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("StakedId"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NetMovement")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<double>("Staked")
                        .HasColumnType("double");

                    b.Property<double>("TotalMovement")
                        .HasColumnType("double");

                    b.Property<double>("Unstaked")
                        .HasColumnType("double");

                    b.HasKey("StakedId");

                    b.HasIndex("Date");

                    b.ToTable("staked_info", (string)null);
                });

            modelBuilder.Entity("ChainflipInsights.EntityFramework.SwapInfo", b =>
                {
                    b.Property<ulong>("SwapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("SwapId"));

                    b.Property<string>("Broker")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<double>("DeltaUsd")
                        .HasColumnType("double");

                    b.Property<double>("DeltaUsdPercentage")
                        .HasColumnType("double");

                    b.Property<double>("DepositAmount")
                        .HasColumnType("double");

                    b.Property<double>("DepositValueUsd")
                        .HasColumnType("double");

                    b.Property<string>("DestinationAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<double>("EgressAmount")
                        .HasColumnType("double");

                    b.Property<double>("EgressValueUsd")
                        .HasColumnType("double");

                    b.Property<string>("ExplorerUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTimeOffset>("SwapDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SwapId");

                    b.HasIndex("SwapDate");

                    b.ToTable("swap_info", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
