name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io
  BUILD_PREFIX: "8.0"
  PROJECT_NAME: chainflip-insights
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Inspect builder
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Build and push
        uses: docker/build-push-action@v6.3.0
        with:
          context: .
          file: Dockerfile
          build-args: |
            "BUILD_NUMBER=${{ env.BUILD_PREFIX }}.${{ github.run_number }}"
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/cumpsd/${{ env.PROJECT_NAME }}:latest
            ${{ env.DOCKER_REGISTRY }}/cumpsd/${{ env.PROJECT_NAME }}:v${{ env.BUILD_PREFIX }}.${{ github.run_number }}
                        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.BUILD_PREFIX }}.${{ github.run_number }}
          release_name: v${{ env.BUILD_PREFIX }}.${{ github.run_number }}
          draft: false
          prerelease: true
          body: |
            ${{ github.event.head_commit.message }}
            Packages available at https://github.com/CumpsD/chainflip-insights/pkgs/container/chainflip-insights
